### ISSUE TITLE
Fix css bug

### ISSUE THREAD

**Issue by ledfordjs** [brookespiker/brooke-portfolio#1]
# This section needs to be styled

![screen shot 2015-11-21 at 12 27 09 am](https://cloud.githubusercontent.com/assets/6081243/11316874/baee5daa-8fe6-11e5-8c51-852712993a8d.jpg)

**Comment by brookespiker** [comment]
# Added style to section! Love you bunchies! <3

## P.S- MAKE ME FOOD
